### ISSUE TITLE
AgreementRoutesProvider.php location is incorrect

### ISSUE THREAD

**Issue by iyyappanuni** [mradcliffe/agreement#2]
Please change the location of AgreementRouteProvider.php file to Entity\Routing\AgreementRouteProvider.php

**Comment by mradcliffe** [comment]
Yep, that's wrong :(. Thank you for reporting the issue.

I haven't gotten started on porting the simpletests over to FunctionalJavascript tests yet if you would also like to do that.

Unfortunately I haven't heard back about getting access to create branches on the drupal.org repository.

**Comment by iyyappanuni** [comment]
Ok. Thank you

**Comment by mradcliffe** [comment]
Fixed as part of refactoring in c0b0b9e to make the module actually work. Probably best to uninstall completely if you have it installed somewhere.
